### ISSUE TITLE
Mapa mental-Erik Israel Cuevas Hernández 

### ISSUE THREAD

**Issue by ErikCuevas03** [SistemasTecTlaxiaco/actividad-1-mapa-mental-ErikCuevas03#2]
![INVESTIGACIÓN
DOCUMENTAL_202273_16185](https://user-images.githubusercontent.com/112439930/188029558-21e18a49-b6c7-403c-a081-572f3ff57bb5.png)

**Comment by josealfredo79** [comment]
Calificacion 17 puntos

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
